### ISSUE TITLE
Suggestion: Add acknowledgments/credits to your Readme.md

### ISSUE THREAD

**Issue by anthonycaccese** [soaremicheledavid/ES-Theme-MINIMA#1]
I was looking at your theme and it's very nice, great work!

One thing I would ask/suggest is that you add a section to your readme that provides acknowledgments/credits to the resources that were leveraged to create the theme.  This is quite customary among theme developers and is very much appreciated (also some licensees may require it)

In the case of the minima theme, as it looks like some of its aspects have been based on the [art-book-next](https://github.com/anthonycaccese/art-book-next-es-de) theme, I would recommend starting with the following:

```
## **Acknowledgments**
* Most system logos were sourced and modified from the excellent work done by Dan Patrick [here](https://archive.org/details/console-logos-professionally-redrawn-plus-official-versions).  They have been modified to be compatible with EmulationStation's current SVG support.
* ChangaOne font is by [Eduardo Tunni](https://www.fontsquirrel.com/fonts/changa)
* Oxygen font is by [Vernon Adams](https://www.fontsquirrel.com/fonts/oxygen)
* Metadata & Menu Icons sourced from [FontAwesome](https://fontawesome.com/search?o=r&m=free)
* Gamelist layout and `theme-customizations` approach were sourced from [Art-Book-Next](https://github.com/anthonycaccese/art-book-next-es) by [Anthony Caccese](https://github.com/anthonycaccese)
```

The above references the sources from the Art-Book-Next theme to make sure that credit is persisted through. Please of course add to it if there are other sources you would like to credit.  Thank you and great work again.

**Comment by soaremicheledavid** [comment]
Hello,

This was  my first theme for batocera, was looking at your theme for
reference, to see how you did some things, thanks for you guidance, just
updated the readme with those acknowledgments. Was used making themes for
ArkOS, they have similar codes and layouts, just made a new theme (CarbonX)
using my old work from that OS, only used the system logos from MINIMA
theme.

Thanks,
Wish you a great day!

În joi, 8 feb. 2024 la 14:29, anthonycaccese ***@***.***> a
scris:

**Comment by anthonycaccese** [comment]
Glad to have helped, and I'm glad to answer questions if you have any regarding Batocera's theme engine.   Thank you for updating the readme.

Great work on the theme, its nice, clean and easy to follow ❤️
